language: c
compiler:
  - clang
  - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev arduino-core
script: "make && make tests"
notifications:
  irc:
    channels:
      - "chat.freenode.org#titoufaitdestests"
    template:
      - "%{repository_name} (%{branch}:%{commit}) %{commit_message} : %{message}"
      - "Build details: %{build_url}"
    on_success: change
    on_failure: always
